### ISSUE TITLE
Unable to find 'java/nio/charset/Charset.gwt.xml'

### ISSUE THREAD

**Issue by freddyboucher** [ManfredTremmel/gwt-bean-validators#1]
First thanks for your lib! GWT Bean Validation has been waiting for a maintainer for a long long time.

I followed the README and added the[ maven dependencies](https://github.com/ManfredTremmel/gwt-bean-validators#maven-integraten) but probably something is missing:

```
[INFO] Super Dev Mode starting up
[INFO]    workDir: /Users/fboucher/Programming/workspace/LearnKeeper/learnkeeper-client/target/gwt/codeserver
[INFO]    Loading inherited module 'com.learnkeeper.App'
[INFO]       Loading inherited module 'de.knightsoftnet.validators.GwtBeanValidators'
[INFO]          Loading inherited module 'org.apache.commons.GWTCommonsLang3'
[INFO]             Loading inherited module 'java.nio.charset.Charset'
[INFO]                [ERROR] Unable to find 'java/nio/charset/Charset.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?
```

Thanks

**Comment by freddyboucher** [comment]
@ManfredTremmel 
It seems like **java.nio.charset.Charset** comes from **gwt-mt-widgets-spring-gwtp** dependency in your [sample app](https://github.com/ManfredTremmel/gwt-bean-validators-example)

But without this dependency your lib doesn't seem to work.

**Comment by freddyboucher** [comment]
It seems to be a wrong alarm.
I tested it on another demo project https://github.com/freddyboucher/gwt-storage-objectify/commit/a5d9e604be0fa9e8d71065fbcb8bcdecadb143a9 and it works (except that App Engine is not compatible with hibernate 5.2.x version!).

**Comment by ManfredTremmel** [comment]
The dependency:tree of my test project shows me guava-gwt is included by gwt-pushstate:

```
[INFO] +- de.knightsoft-net:gwt-pushstate:jar:2.0.0.6:provided
[INFO] |  \- de.knightsoft-net:gwt-commons-lang3:jar:3.4-2:compile
[INFO] |     \- com.google.guava:guava-gwt:jar:19.0:compile
```

But gwt-commons-lang3 is also a dependency of gwt-bean-validators.
For App Engine compatibility it looks like I have to switch to hibernate validator 5.3.x as far as I understand https://hibernate.atlassian.net/browse/HV-1023 but it's in alpha state at the moment...

**Comment by ManfredTremmel** [comment]
Hm, where's my yesterdays comment, didn't I commit it?
@freddyboucher " java/nio/charset/Charset.gwt.xml" is part of guava-gwt 19.0, if it's missing in one of your projects,  lets look at the dependencies (mvn dependency:tree), maybe a older version was included?

**Comment by ManfredTremmel** [comment]
Hello @freddyboucher, I've updated gwt-bean-validators to 0.21.0, which uses now hibernate-validator 5.3.2. I hope this solves the problems with App Engine. Can you test again?

**Comment by freddyboucher** [comment]
@ManfredTremmel 
I found some time to test it but still not compatible :(

https://github.com/freddyboucher/gwt-storage-objectify/commit/7cbd0fc2010e703a03fefbdefa4c92cb1da263b4

**Comment by ManfredTremmel** [comment]
Hello @freddyboucher ,
sorry for ignoring your report so long, but now, after migrating to validation-api 2.0.1 and hibernate-validator 6.0.7.Final, I've tried again with your project and - tatarata - it worked here.
I've attached the changes as patchfile (against master branch):

[gwt-storage-objectify_gwt-bean-validators.patch.txt](https://github.com/ManfredTremmel/gwt-bean-validators/files/1628836/gwt-storage-objectify_gwt-bean-validators.patch.txt)

Let me know if it's ok for you and I can close the ticket.

**Comment by ManfredTremmel** [comment]
Problem is fixed, patch was accepted, bug can be closed.
