### ISSUE TITLE
Compile error:

### ISSUE THREAD

**Issue by diskostu** [ManfredTremmel/gwt-bean-validators#9]
Hi Manfred,

I recently included your lib in a new project. I followed your instructions, but I get a compile error:

```
[INFO] Compiling module de.axa.security.ppac.v2.ppac_v2
[INFO]    Tracing compile failure path for type 'com.google.web.bindery.requestfactory.shared.impl.AbstractRequestContext'
[INFO]       [ERROR] Errors in 'jar:file:/C:/DEV/paas/lib/m3-repository/com/google/gwt/gwt-user/2.8.2/gwt-user-2.8.2.jar!/com/google/web/bindery/requestfactory/shared/impl/AbstractRequestContext.java'
[INFO]          [ERROR] Line 418: The type AbstractRequestContext.MyConstraintViolation must implement the inherited abstract method ConstraintViolation<BaseProxy>.getExecutableParameters()
[INFO]          [ERROR] Line 418: The type AbstractRequestContext.MyConstraintViolation must implement the inherited abstract method ConstraintViolation<BaseProxy>.getExecutableReturnValue()
[INFO]          [ERROR] Line 418: The type AbstractRequestContext.MyConstraintViolation must implement the inherited abstract method ConstraintViolation<BaseProxy>.unwrap(Class<U>)
[INFO]    [ERROR] Aborting compile due to errors in some input files
```

Do you have any idea what's the problem here?

**Comment by ManfredTremmel** [comment]
Hello @diskostu ,
I haven't used the request factory in my own projects, so I haven't had this problem. As far as I can see, the MyConstraintViolation class should implement ConstraintViolation, but it's only compatible with javax.validation 1.0 and not with 1.1 or later.
I'll try to create a replacement for it, at the moment it simply doesn't work, sorry.

**Comment by ManfredTremmel** [comment]
Hello @diskostu ,
can you retry with the new released version 0.51.1? It should fix the compile error.

**Comment by diskostu** [comment]
Hi Manfred,

I will try it tomorrow in the office and give you feedback. Thanks!

Denny

Am 11.01.2018 22:49 schrieb "Manfred Tremmel" <notifications@github.com>:

**Comment by diskostu** [comment]
Hi Manfred, the new version works very well. Thank you for your fast fix.

**Comment by ManfredTremmel** [comment]
You are wellcome.
